# Generated by Django 4.2.4 on 2023-09-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0003_alter_menumodel_name_alter_menumodel_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranger.menu')),
            ],
        ),
        migrations.RenameModel(
            old_name='NotesModel',
            new_name='Note',
        ),
        migrations.DeleteModel(
            name='MenuModel',
        ),
    ]
