# Generated by Django 4.2.4 on 2023-09-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0005_secondcase_firstcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='secondcase',
            name='parent',
        ),
        migrations.DeleteModel(
            name='FirstCase',
        ),
        migrations.DeleteModel(
            name='SecondCase',
        ),
    ]
