# Generated by Django 4.2.4 on 2023-09-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0006_case_remove_secondcase_parent_delete_firstcase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMenuRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranger.case')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranger.menu')),
            ],
        ),
    ]
