# Generated by Django 4.2.4 on 2023-09-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0008_case_menu_delete_casemenurelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='menu',
            new_name='menus',
        ),
    ]
