# Generated by Django 4.2.4 on 2023-09-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0010_note_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
