# Generated by Django 4.2.4 on 2023-09-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0012_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('title', 'case')},
        ),
    ]
